name: alley_planets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  go_router: ^15.1.2
  crypto: ^3.0.6
  riverpod_annotation: ^2.6.1
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.6.4
  freezed: ^2.4.5
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
  assets:
    - assets/planets/